### ISSUE TITLE
Decode without converting to File

### ISSUE THREAD

**Issue by And96** [fisherman-23/colorgram-dart#2]
Why decoding from File? Is possible to get color directly from Image object or ImageProvider?
Wouldn't it be much simpler and faster, as well as getting clearer code?

And it can easily get colors from **web-url** too. Using mixed with **CachedNetworkImageProvider**

Example of others color extraction libraries. 

### e.g. using **Material** function
//import 'package:flutter/material.dart';
![immagine](https://github.com/fisherman-23/colorgram-dart/assets/42185838/db9394c2-d1a1-4292-9560-733c3606609b)
 ` 
   final ColorScheme paletteGenerator =
            await ColorScheme.fromImageProvider(
                    provider: Image(
                      image: ResizeImage(
                        CachedNetworkImageProvider(
                          url,
                          errorListener: (value) {},
                        ),
                        width: 10,
                        height: 10,
                      ),
                    ).image,
                    brightness: Brightness.light)
                .timeout(Duration(milliseconds: timeout));
        Color colorImg = paletteGenerator.surfaceTint;`

or

### e.g. using **PaletteGenerator** library
//import 'package:palette_generator/palette_generator.dart';
![immagine](https://github.com/fisherman-23/colorgram-dart/assets/42185838/77c22b54-9423-46a1-9989-cedf635ecee2)
`PaletteGenerator paletteGenerator;
        paletteGenerator = await PaletteGenerator.fromImageProvider(
          Image(
            image: ResizeImage(
              CachedNetworkImageProvider(
                url,
                errorListener: (value) {},
              ),
              width: 10,
              height: 10,
            ),
          ).image,
          size: const Size(10, 10),
          maximumColorCount: 1,
        ).timeout(Duration(milliseconds: timeout));
        Color paletteColor = paletteGenerator.dominantColor!.color;`

**Comment by fisherman-23** [comment]
2.0.0 now supports ImageProvider as an input instead of File :)
